# Generated by Django 4.2.2 on 2023-08-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lastUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.user')),
            ],
            options={
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
