# Generated by Django 4.2.2 on 2023-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='lastUpdated',
        ),
        migrations.AddField(
            model_name='user',
            name='prefer',
            field=models.CharField(default='weekly', max_length=10),
        ),
    ]
